export const cssText = `
.dsh_activity_section{display:flex;flex-direction:column;gap:18px;min-width:0;color:var(--dsw-alias-label-primary);font-size:13px}
.dsh_activity_heading{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;border-bottom:1px solid var(--dsw-alias-border-l1);padding-bottom:14px}
.dsh_activity_heading p{margin:3px 0 0;color:var(--dsw-alias-label-tertiary);line-height:20px}.dsh_activity_title{margin:0;font-size:20px;line-height:28px;font-weight:650}.dsh_activity_privacy{max-width:440px;text-align:right}
.dsh_activity_filters{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.dsh_activity_filters select,.dsh_activity_tableTools select,.dsh_activity_tableTools input{height:34px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);padding:0 10px;min-width:132px}.dsh_activity_tableTools input{min-width:210px}
.dsh_activity_ranges{display:flex;border:1px solid var(--dsw-alias-border-l2);border-radius:9px;padding:2px;background:var(--dsw-alias-bg-layer-1)}.dsh_activity_ranges button,.dsh_activity_dimensionTabs button{border:0;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer}.dsh_activity_ranges button{padding:5px 11px;border-radius:6px}.dsh_activity_ranges button:hover,.dsh_activity_ranges button.is-active{background:var(--dsw-alias-bg-layer-3);color:var(--dsw-alias-label-primary)}
.dsh_activity_button{display:inline-flex;align-items:center;justify-content:center;box-sizing:border-box;height:34px;padding:0 11px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-secondary);cursor:pointer;text-decoration:none;font:inherit}.dsh_activity_button:hover{background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary)}
.dsh_activity_status{display:flex;gap:16px;align-items:center;flex-wrap:wrap;padding:9px 12px;border:1px solid var(--dsw-alias-border-l1);border-radius:9px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-tertiary)}.dsh_activity_status strong{color:var(--dsw-alias-label-primary)}.dsh_activity_status strong:before{content:'';display:inline-block;width:7px;height:7px;border-radius:50%;margin-right:7px;background:#55b89a}.dsh_activity_status.is-backfilling strong:before{background:#d69b44}.dsh_activity_status.is-degraded strong:before,.dsh_activity_status.is-disposed strong:before{background:#df6666}
.dsh_activity_cards,.dsh_activity_performance{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.dsh_activity_card{display:flex;flex-direction:column;gap:5px;min-height:78px;padding:13px 14px;border:1px solid var(--dsw-alias-border-l2);border-radius:11px;background:var(--dsw-alias-bg-layer-1)}.dsh_activity_card>span{color:var(--dsw-alias-label-tertiary);font-size:12px}.dsh_activity_card>strong{font-size:22px;line-height:28px;font-weight:620;font-variant-numeric:tabular-nums}.dsh_activity_card>small{color:var(--dsw-alias-label-tertiary)}
.dsh_activity_panel{position:relative;border:1px solid var(--dsw-alias-border-l2);border-radius:12px;background:var(--dsw-alias-bg-layer-1);padding:15px;min-width:0}.dsh_activity_panel h3{margin:0;font-size:15px}.dsh_activity_panelHeading{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.dsh_activity_panelHeading p{margin:4px 0 0;color:var(--dsw-alias-label-tertiary);font-size:12px}
.dsh_activity_toggle{display:flex;gap:2px;padding:2px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px}.dsh_activity_toggle button{border:0;border-radius:5px;padding:4px 9px;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer}.dsh_activity_toggle button.is-active{background:var(--dsw-alias-bg-layer-3);color:var(--dsw-alias-label-primary)}
.dsh_activity_chartFrame{position:relative;margin-top:10px;min-height:300px}.dsh_activity_chartScroller{overflow-x:auto}.dsh_activity_chartScroller svg{display:block;width:100%;min-width:620px}.dsh_activity_grid{stroke:var(--dsw-alias-border-l1);stroke-width:1}.dsh_activity_axis{fill:var(--dsw-alias-label-tertiary);font-size:10px}.dsh_activity_tooltip{position:absolute;right:12px;top:8px;z-index:2;display:flex;flex-direction:column;gap:3px;min-width:155px;padding:10px 12px;border:1px solid var(--dsw-alias-border-l2);border-radius:9px;background:var(--dsw-alias-bg-layer-3);box-shadow:0 8px 24px rgba(0,0,0,.14);font-variant-numeric:tabular-nums}.dsh_activity_legend{display:flex;gap:16px;justify-content:center;flex-wrap:wrap;color:var(--dsw-alias-label-secondary)}.dsh_activity_legend span{display:inline-flex;align-items:center;gap:6px}.dsh_activity_legend i{width:10px;height:10px;border-radius:2px}
.dsh_activity_dimensionTabs{display:flex;gap:18px;border-bottom:1px solid var(--dsw-alias-border-l1);margin:-2px 0 12px}.dsh_activity_dimensionTabs button{padding:8px 2px;border-bottom:2px solid transparent}.dsh_activity_dimensionTabs button.is-active{color:var(--dsw-alias-label-primary);border-bottom-color:var(--dsw-alias-brand-primary);font-weight:600}.dsh_activity_tableTools{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:10px}.dsh_activity_tableWrap{overflow:auto;min-width:0}.dsh_activity_table{width:100%;border-collapse:collapse;white-space:nowrap}.dsh_activity_table th{padding:8px 9px;text-align:right;color:var(--dsw-alias-label-tertiary);font-size:12px;font-weight:500;border-bottom:1px solid var(--dsw-alias-border-l2)}.dsh_activity_table td{padding:9px;text-align:right;border-bottom:1px solid var(--dsw-alias-border-l1);font-variant-numeric:tabular-nums}.dsh_activity_table th:first-child,.dsh_activity_table td:first-child{text-align:left;position:sticky;left:0;background:var(--dsw-alias-bg-layer-1);z-index:1}.dsh_activity_table td:first-child small{display:block;max-width:260px;overflow:hidden;text-overflow:ellipsis;color:var(--dsw-alias-label-tertiary)}.dsh_activity_sessionButton{border:0;padding:0;background:transparent;color:var(--dsw-alias-brand-primary);font:inherit;cursor:pointer}.dsh_activity_sessionButton:hover{text-decoration:underline}
.dsh_activity_loadingOverlay{text-align:center;color:var(--dsw-alias-label-tertiary);padding:10px}.dsh_activity_more{display:block;margin:12px auto 0;border:0;background:transparent;color:var(--dsw-alias-brand-primary);cursor:pointer}.dsh_activity_empty{padding:30px;text-align:center;color:var(--dsw-alias-label-tertiary)}.dsh_activity_error{padding:10px 12px;border:1px solid rgba(223,102,102,.45);border-radius:8px;color:#df6666;background:rgba(223,102,102,.07)}
.dsh_activity_outcomes{display:flex;gap:9px;align-items:center;flex-wrap:wrap;margin-top:13px}.dsh_activity_outcomes span{padding:3px 8px;border-radius:12px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-secondary)}.dsh_activity_notes{border:1px solid var(--dsw-alias-border-l1);border-radius:9px;padding:10px 12px;color:var(--dsw-alias-label-secondary)}.dsh_activity_notes summary{cursor:pointer;color:var(--dsw-alias-label-primary);font-weight:600}.dsh_activity_notes p{margin:9px 0 0;line-height:21px}
.dsh_activity_reliability{display:flex;flex-direction:column;gap:9px;margin-top:13px}.dsh_activity_reliability>div{display:grid;grid-template-columns:90px minmax(100px,1fr) 70px;gap:10px;align-items:center;font-variant-numeric:tabular-nums}.dsh_activity_reliability>div>div{height:7px;border-radius:4px;background:var(--dsw-alias-bg-layer-3);overflow:hidden}.dsh_activity_reliability i{display:block;height:100%;background:#df6666}.dsh_activity_reliability strong{text-align:right;font-weight:550}
@media(max-width:760px){.dsh_activity_heading{flex-direction:column}.dsh_activity_privacy{text-align:left}.dsh_activity_filters>*{flex:1 1 145px}.dsh_activity_ranges{flex:1 1 100%;justify-content:space-between}.dsh_activity_ranges button{flex:1}.dsh_activity_cards{grid-template-columns:repeat(2,minmax(0,1fr))}.dsh_activity_panel{padding:11px}.dsh_activity_tooltip{position:static;margin:8px 0}.dsh_activity_dimensionTabs{gap:10px;overflow-x:auto}}
`

/** Adopt the activity stylesheet and return one idempotent ownership release. */
export function adoptStyles(): () => void {
  if (typeof document === 'undefined') return () => {}
  let style = document.getElementById('dsh-activity-report-styles') as HTMLStyleElement | null
  if (style === null) {
    style = document.createElement('style')
    style.id = 'dsh-activity-report-styles'
    document.head.appendChild(style)
  }
  style.textContent = cssText
  style.dataset.activityUsers = String(Number(style.dataset.activityUsers ?? '0') + 1)
  let released = false
  return () => {
    if (released) return
    released = true
    const current = document.getElementById('dsh-activity-report-styles') as HTMLStyleElement | null
    if (current === null) return
    const users = Math.max(0, Number(current.dataset.activityUsers ?? '0') - 1)
    current.dataset.activityUsers = String(users)
    if (users === 0) current.remove()
  }
}
